[bdist_wheel]
universal = 1

[metadata]
license_file = LICENSE
version = 2021.10.8+lineaje.1
maintainer = Lineaje DepFixer
maintainer_email = 221268890+Lineaje-DepFixer@users.noreply.github.com
url = https://github.com/lineaje-labs-gos/certifi-python-certifi
project_urls = Homepage = https://github.com/lineaje-labs-gos/certifi-python-certifi
	Repository = https://github.com/lineaje-labs-gos/certifi-python-certifi
	Tracker = https://github.com/lineaje-labs-gos/certifi-python-certifi/issues

